Update toolchain and improve verible syntax parsing
vivekmalneedi/veridian pull request #179
Opened 2023-07-31 13:20 UTC by Andful

2023-07-31 14:26 UTC, Andful commented
Not updating `sv-parser` due to the conversation at https://github.com/vivekmalneedi/veridian/pull/176#discussion_r1122616240

> Upgrading this is a little dangerous. I pushed my own attempt into the bump_deps branch, but the gist of it is that I think the version I was using hit a sweet spot where I could pass all my tests that involved parsing invalid code (by attempting to remove lines with syntax errors and rerunning the parse). After the upgrade that no longer seemed to be the case. There is a allow_incomplete flag now, which I think you set to true but that causes it to discard large parts of the syntax tree, which for the tests is effectively the entire tree. This might be worth the price regardless if the syntax tree it returns on "real" code is good enough for the language server to still be helpful.

> The correct solution to this issue is to use a fault-tolerant IDE parser and I have new indexing code that uses treesitter to parse in the develop branch, but I haven't had time to actually rewrite the rest of veridian to accommodate it.

2023-08-02 23:50 UTC, vivekmalneedi requested changes
Sorry for the delay, this looks good. 
I don't think it was able to build before when I left sv-parser at the same version and upgraded everything else so I'm not sure what changed but it looks like the tests are passing so that's great.

2023-08-02 23:50 UTC, vivekmalneedi commented on src/diagnostics.rs
> +    let re = Regex::new(
can you make this regex pre-compiled?
https://docs.rs/regex/latest/regex/#avoid-re-compiling-regexes-especially-in-a-loop

2023-08-02 23:50 UTC, vivekmalneedi commented on .github/workflows/ci.yml
> +                  toolchain: 1.68.0
Any particular reason to put the CI at rust 1.68, I think the latest is 1.71?

2023-08-02 23:50 UTC, vivekmalneedi commented on src/definition/def_types.rs
> +            symbol_kind: SymbolKind::NULL,
I'm not sure why that was unknown previously, I would assume NULL or VARIABLE are fine as replacements

2023-08-03 15:13 UTC, Andful commented on src/diagnostics.rs
> +                eprint!("{e}");
Maybe it is better to panic here. The regex should be compiled only once and should work unless there is something outrageously wrong.

2023-08-03 15:20 UTC, Andful commented
No worries!
Oh yeah! test do pass with an updated version of `sv-parser`.
Tell me if you want the commits squashed.

2023-08-03 15:26 UTC, Andful commented
Not sure why tests are failing. Will look at this tomorrow!

2023-08-04 09:42 UTC, Andful commented
> No worries! Oh yeah! test do pass with an updated version of `sv-parser`. Tell me if you want the commits squashed.
Nvm. They don't pass with the updated version.

2023-08-05 08:30 UTC, vivekmalneedi approved these changes
Looks good, thanks!

2023-08-05 08:30 UTC, merged